version: '2'
services:

    hub:
        image: "selenium/standalone-chrome:latest"
        volumes:
            - /dev/shm:/dev/shm
        ports:
            - "4444:4444"
    
    bot:
        # use the image or use the source with this line # build: .
        image: docker.pkg.github.com/smf33/flickrfollowerbot/flickrfollowerbot:latest
        depends_on:
            - hub
        volumes:
            - .:/local
        environment:
            - SeleniumRemoteServer=hub
            - BotUserSaveFolder=/local
            # if set, use the host env variable 
            - BotUserEmail
            - BotUserPassword
            - BotTasks
