version: '2'
services:

    hub:
        image: "selenium/standalone-chrome:latest"
        volumes:
            - /dev/shm:/dev/shm
        ports:
            - "4444:4444"
    
    bot:
        # comment next line if you want to use the officiel github repo (a "docker login" will be required by github)
        build: .
        image: docker.pkg.github.com/smf33/flickrfollowerbot/flickrfollowerbot:latest
        depends_on:
            - hub
        volumes:
            - .:/local
        environment:
            - SeleniumRemoteServer=hub
            - BotUserSaveFolder=/local
            # if set, use the host env variable 
            - BotUserEmail
            - BotUserPassword
            - BotTasks
